name: Run test script
run: python ./test_script.py
working-directory: /home/runner/work/distance_classification/distance_classification


on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install numpy pandas scikit-learn

      - name: Run test script
        run: python test_script.py
